export const NanumPosts = [
  {
    id: 1,
    accountName: "ththt",
    title: "첫 번째 글",
    content: "감자깡",
    nickname: "작성자1",
    views: 120,
    date: "2024-02-13",
    likes: 5,
    nanum: "O",
  },
  {
    id: 2,
    accountName: "ththt",
    title: "두 번째 글",
    content: "고구마깡",
    nickname: "작성자2",
    views: 5,
    date: "2024-02-14",
    likes: 7,
    nanum: "O",
  },
  {
    id: 3,
    title: "세 번째 글",
    content: "감자깡",
    nickname: "작성자1",
    views: 10,
    date: "2024-02-13",
    likes: 5,
    nanum: "O",
  },
  {
    id: 4,
    title: "네 번째 글",
    content: "고구마깡",
    nickname: "작성자2",
    views: 5,
    date: "2024-02-14",
    likes: 7,
    nanum: "O",
  },
  {
    id: 5,
    title: "다섯 번째 글",
    content: "감자깡",
    nickname: "작성자1",
    views: 10,
    date: "2024-02-13",
    likes: 5,
    nanum: "O",
  },
  {
    id: 6,
    title: "여섯 번째 글",
    content: "양파깡",
    nickname: "작성자2",
    views: 2424,
    date: "2024-02-28",
    likes: 345,
    nanum: "O",
  },
  {
    id: 7,
    title: "일곱 번째 글",
    content: "감자깡",
    nickname: "작성자1",
    views: 10,
    date: "2024-02-13",
    likes: 5,
    nanum: "X",
  },
  {
    id: 8,
    title: "여덟 번째 글",
    content: "고구마깡",
    nickname: "작성자2",
    views: 5,
    date: "2024-02-14",
    likes: 7,
    nanum: "X",
  },
  {
    id: 9,
    title: "아홉 번째 글",
    content: "감자깡",
    nickname: "작성자1",
    views: 10,
    date: "2024-02-13",
    likes: 5,
    nanum: "X",
  },
  {
    id: 10,
    title: "열 번째 글",
    content: "고구마깡",
    nickname: "작성자2",
    views: 5,
    date: "2024-02-14",
    likes: 7,
    nanum: "X",
  },
  {
    id: 11,
    title: "열한 번째 글",
    content: "감자깡",
    nickname: "작성자11",
    views: 10,
    date: "2024-02-13",
    likes: 5,
    nanum: "X",
  },
  {
    id: 12,
    title: "열두 번째 글열두 번째 글열두 번째 글열두 번째 글열두 번째 글",
    content: "고구마깡",
    nickname: "작성자12",
    views: 5,
    date: "2024-02-14",
    likes: 7,
    nanum: "X",
  },
];
