export const Trash = [
  {
    id: 1,
    name: "생수병",
    quality: "페트병",
    keywords: "#페트병 #페트",
    rules: "어쩌구",
    image: "/images/search/pett_bottle.jpg",
  },
  {
    id: 2,
    name: "맥주병",
    quality: "유리병",
    keywords: "유리병",
    rules: "저쩌구",
    image: "/images/search/barley_bottle.jpg",
  },
  {
    id: 3,
    name: "소주병",
    quality: "유리병",
    keywords: "유리병",
    rules: "이러쿵",
    image: "/images/search/soju_bottle.jpg",
  },
  {
    id: 4,
    name: "폐의약품",
    quality: "기타",
    keywords: "약품",
    rules: "가까운 보건소나 약국, 아파트 관리사무소 등에 버려주세요",
    image: "/images/search/old_medicine.jpg",
  },
  {
    id: 5,
    name: "폐건전지",
    quality: "건전지",
    keywords: "건전지",
    rules: "저러쿵",
    image: "/images/search/old_battery.jpg",
  },
  {
    id: 6,
    name: "유리병",
    quality: "유리병",
    keywords: "#유리 #유리병",
    rules: "불라불라",
    image: "/images/search/glass_bottle.png",
  },
];
